export const PERMISSIONS = [
  'dashboard.read',
  'leads.read',
  'leads.write',
  'leads.delete',
  'leads.import',
  'leads.assign',
  'leads.merge',
  'customers.read',
  'customers.write',
  'whatsapp.read',
  'whatsapp.send',
  'campaigns.read',
  'campaigns.write',
  'campaigns.approve',
  'campaigns.send',
  'meetings.read',
  'meetings.write',
  'calls.read',
  'calls.write',
  'recordings.read',
  'knowledge.read',
  'knowledge.write',
  'reports.read',
  'users.read',
  'users.write',
  'audit.read',
  'notifications.read',
  'settings.write',
] as const;

export type PermissionCode = (typeof PERMISSIONS)[number];

export const ROLE_NAMES = [
  'ADMIN',
  'MARKETING_MANAGER',
  'MARKETING_EXECUTIVE',
  'SALES',
  'MANAGEMENT',
] as const;

export type RoleName = (typeof ROLE_NAMES)[number];

export const PERMISSION_DESCRIPTIONS: Record<PermissionCode, string> = {
  'dashboard.read': 'View the management dashboard',
  'leads.read': 'View leads',
  'leads.write': 'Create and update leads',
  'leads.delete': 'Delete leads',
  'leads.import': 'Import leads',
  'leads.assign': 'Assign leads',
  'leads.merge': 'Merge duplicate leads',
  'customers.read': 'View customers',
  'customers.write': 'Update customers',
  'whatsapp.read': 'View WhatsApp conversations',
  'whatsapp.send': 'Send WhatsApp messages',
  'campaigns.read': 'View campaigns',
  'campaigns.write': 'Create and edit campaigns',
  'campaigns.approve': 'Approve campaigns',
  'campaigns.send': 'Send or execute campaigns',
  'meetings.read': 'View meetings',
  'meetings.write': 'Book and change meetings',
  'calls.read': 'View calls',
  'calls.write': 'Create calls and voice-bot sessions',
  'recordings.read': 'Play call recordings',
  'knowledge.read': 'View the knowledge base',
  'knowledge.write': 'Edit the knowledge base',
  'reports.read': 'View and export reports',
  'users.read': 'View users',
  'users.write': 'Manage users and roles',
  'audit.read': 'View audit logs',
  'notifications.read': 'View notifications',
  'settings.write': 'Change CRM settings',
};

const READ_ONLY: PermissionCode[] = [
  'dashboard.read',
  'leads.read',
  'customers.read',
  'whatsapp.read',
  'campaigns.read',
  'meetings.read',
  'calls.read',
  'recordings.read',
  'knowledge.read',
  'reports.read',
  'users.read',
  'audit.read',
  'notifications.read',
];

export const ROLE_PERMISSIONS: Record<RoleName, PermissionCode[]> = {
  ADMIN: [...PERMISSIONS],
  MARKETING_MANAGER: [
    'dashboard.read',
    'leads.read',
    'leads.write',
    'leads.import',
    'leads.assign',
    'leads.merge',
    'customers.read',
    'customers.write',
    'whatsapp.read',
    'whatsapp.send',
    'campaigns.read',
    'campaigns.write',
    'campaigns.approve',
    'campaigns.send',
    'meetings.read',
    'meetings.write',
    'calls.read',
    'recordings.read',
    'knowledge.read',
    'knowledge.write',
    'reports.read',
    'users.read',
    'notifications.read',
  ],
  MARKETING_EXECUTIVE: [
    'dashboard.read',
    'leads.read',
    'leads.write',
    'leads.import',
    'customers.read',
    'whatsapp.read',
    'whatsapp.send',
    'campaigns.read',
    'campaigns.write',
    'campaigns.send',
    'meetings.read',
    'meetings.write',
    'knowledge.read',
    'notifications.read',
  ],
  SALES: [
    'dashboard.read',
    'leads.read',
    'leads.write',
    'leads.import',
    'leads.assign',
    'customers.read',
    'customers.write',
    'whatsapp.read',
    'whatsapp.send',
    'campaigns.read',
    'meetings.read',
    'meetings.write',
    'calls.read',
    'calls.write',
    'recordings.read',
    'knowledge.read',
    'notifications.read',
  ],
  MANAGEMENT: READ_ONLY,
};

export function roleHasPermission(role: RoleName, permission: string): boolean {
  return ROLE_PERMISSIONS[role].includes(permission as PermissionCode);
}
